spring:

  datasource:
    driver-class-name: org.h2.Driver

    # In-memory H2 database
    url: jdbc:h2:mem:${application.datasource.name};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

    username: sa
    password: ~

  h2:
    server:
      enabled: false
    console:
      enabled: false # Enables the H2 console at /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true  # Logs SQL statements
    hibernate:
      ddl-auto: none  # or use "create-drop" to drop tables on shutdown
      properties:
        javax.persistence.jdbc.blob: true
        hibernate.format_sql: true # Pretty-print SQL logs (useful with show_sql enabled)
        hibernate.use_sql_comments: true # Add comments to SQL for better traceability
        hibernate.generate_statistics: false # Disable for production; enable for performance debugging

  sql:
    init:
      mode: always  # Ensures SQL scripts run even if an embedded database is not detected

#--------------------
# Logging
#--------------------
logging:
  stdout-appender-threshold-level: TRACE
  trace-appender-threshold-level: TRACE
  level:
    root: INFO
    no.acntech: DEBUG
    org.springframework: INFO
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springdoc: INFO
    org.hibernate: DEBUG
    # Set to DEBUG for logging SQL queries
    org.hibernate.SQL: DEBUG
    # Set to TRACE for logging prepared statement parameters
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.SQL_SLOW: DEBUG